In [272]:
import pandas as pd
import numpy as numpy

### 1) Lire le fichier CSV via Pandas 

In [271]:
missing_values = ["n/a", "na", "--", "nan", "unknown", " "]
df = pd.read_csv('mower_market_snapshot.csv', sep = ';',na_values = missing_values)
df

capacity  failure_rate     id      margin       price   prod_cost  \
0     10.492623      0.042528  18377  633.766584  828.802103  195.035519   
1     20.273730      0.037896  19363  731.576817  882.894916  151.318099   
2     20.190457      0.039111  19641  741.218202  919.355522  178.137319   
3     27.220131      0.041303  18728  654.255635  817.085097  162.829462   
4     16.370911      0.037938  18722  703.094527  844.581465  141.486938   
...         ...           ...    ...         ...         ...         ...   
1394  44.959895      0.234647  18451   63.662561   75.161102   11.498540   
1395  59.356058      0.253694  18663   64.014543   75.395132   11.380589   
1396  67.865222      0.228935  19169   62.132035  810.883148         NaN   
1397  66.855435      0.244948  18946   58.697122   68.491318    9.794197   
1398  54.712713      0.177143  19017   64.259212   74.955428   10.696216   

     product_type quality warranty  market_share  attractiveness  
0     auto-portee     Low     3ans      0.006360        0.650648  
1     auto-portee     Low   3 ans.      0.006840        0.699792  
2     auto-portee     Low    3_ans      0.006179        0.632129  
3     auto-portee     Low   3 anss      0.007925        0.810730  
4     auto-portee  Medium    3ans.      0.007406        0.757614  
...           ...     ...      ...           ...             ...  
1394      essence  Medium     1 an      0.000973        0.513126  
1395      essence     Low     1ans      0.001038        0.547739  
1396      essence     Low     1an.      0.001243        0.655622  
1397      essence     Low     1 an      0.001644        0.867537  
1398      essence     Low     1an.      0.001022        0.538969  

[1399 rows x 11 columns]

### 2) Appliquer le maximum de fonctions issue du support TD sur les données CSV 

In [130]:
series = pd.Series(df['prod_cost'])
series

0       195.03551928211797
1       151.31809934886763
2       178.13731921134948
3       162.82946157588628
4       141.48693796090603
               ...        
1394    11.498540481074583
1395    11.380588736668567
1396               unknown
1397     9.794196773761458
1398    10.696216086742934
Name: prod_cost, Length: 1399, dtype: object

### 3) Auditer et analyser la colonnes Prod_cost 

In [273]:
print(df['prod_cost'].describe())
print(df['prod_cost'].shape)

count    1368.000000
mean       55.434239
std        61.474453
min       -64.000000
25%        10.667699
50%        12.141745
75%       113.655262
max       210.984941
Name: prod_cost, dtype: float64
(1399,)


### 4) Analyser le nombre de valeurs manquantes par colonnes 

In [251]:
for x in df:
    print(x ,df[df[x].isnull()].shape[0])

capacity 0
failure_rate 0
id 0
margin 0
price 0
prod_cost 31
product_type 0
quality 0
warranty 0
market_share 0
attractiveness 0


### 5) Remplacer les valeurs manquantes par la moyenne de la colonne (si possible) 

In [252]:
moyenne = df["prod_cost"].mean()
df["prod_cost"] = df["prod_cost"].fillna(moyenne)

### 6) Afficher les valeurs uniques de la colonne Warranty 

In [253]:
df["warranty"].unique()

array(['3ans', '3 ans.', '3_ans', '3 anss', '3ans.', '3 ans', '3_ans.',
       '3_anss', '3anss', '2 ans', '2 anss', '2anss', '2_ans', '2ans',
       '2_ans.', '2 ans.', '2_anss', '2ans.', '1 an', '1an', '1_an.',
       '1ans', '1an.', '1_ans', '1_an', '1 an.', '1 ans'], dtype=object)

### 7) Traiter la colonne warranty afin d'uniformiser les valeurs (avoir uniquement des valeurs numériques uniformes) 

In [254]:
df["warranty"].shape

(1399,)

In [255]:
df["warranty"] = df["warranty"].str[0].astype(int)

In [256]:
df["warranty"].unique()

array([3, 2, 1])

### 8) Traiter la colonne warranty afin d'obtenir une colonne numérique avec 3 valeurs uniques 

 

In [233]:
df["warranty"].unique() #done

array([3, 2, 1])

### 9) Traiter la colonne price afin d'avoir 3 catégories :  

    - 0-300 

    -301-500 

    - 501- ++ 

In [257]:
category1 = df[(df["price"]>0) & (df["price"]<=300)]
category2 = df[(df["price"]>300) & (df["price"]<=500)]
category3 = df[df["price"]>500]

### 10) Transformer la colonne product_type en colonne numérique avec 3 catégories :  

    1 

    2 

    3 

In [258]:
df["product_type"].unique()

array(['auto-portee', 'electrique', 'essence'], dtype=object)

In [264]:
df.loc[df["product_type"]=='auto-portee',"product_type"]=1
df.loc[df["product_type"]=='electrique',"product_type"]=2
df.loc[df["product_type"]=='essence',"product_type"]=3

In [266]:
df["product_type"].unique()

array([1, 2, 3], dtype=object)

### 11) Puis créer 3 colonnes (auto-portée, essence, électrique) représentant une variable binaire avec 1 si le produit est du type de la colonne ou  0 sinon. 

 

In [267]:
df["auto-portee"]=0
df["electrique"]=0
df["essence"]=0

In [269]:
df.loc[df["product_type"]==1,"auto-portee"]=1
df.loc[df["product_type"]==2,"electrique"]=1
df.loc[df["product_type"]==3,"essence"]=1

In [270]:
df

capacity  failure_rate     id      margin       price   prod_cost  \
0     10.492623      0.042528  18377  633.766584  828.802103  195.035519   
1     20.273730      0.037896  19363  731.576817  882.894916  151.318099   
2     20.190457      0.039111  19641  741.218202  919.355522  178.137319   
3     27.220131      0.041303  18728  654.255635  817.085097  162.829462   
4     16.370911      0.037938  18722  703.094527  844.581465  141.486938   
...         ...           ...    ...         ...         ...         ...   
1394  44.959895      0.234647  18451   63.662561   75.161102   11.498540   
1395  59.356058      0.253694  18663   64.014543   75.395132   11.380589   
1396  67.865222      0.228935  19169   62.132035  810.883148   55.434239   
1397  66.855435      0.244948  18946   58.697122   68.491318    9.794197   
1398  54.712713      0.177143  19017   64.259212   74.955428   10.696216   

     product_type quality  warranty  market_share  attractiveness  \
0               1     Low         3      0.006360        0.650648   
1               1     Low         3      0.006840        0.699792   
2               1     Low         3      0.006179        0.632129   
3               1     Low         3      0.007925        0.810730   
4               1  Medium         3      0.007406        0.757614   
...           ...     ...       ...           ...             ...   
1394            3  Medium         1      0.000973        0.513126   
1395            3     Low         1      0.001038        0.547739   
1396            3     Low         1      0.001243        0.655622   
1397            3     Low         1      0.001644        0.867537   
1398            3     Low         1      0.001022        0.538969   

      auto-portee  electrique  essence  
0               1           0        0  
1               1           0        0  
2               1           0        0  
3               1           0        0  
4               1           0        0  
...           ...         ...      ...  
1394            0           0        1  
1395            0           0        1  
1396            0           0        1  
1397            0           0        1  
1398            0           0        1  

[1399 rows x 14 columns]